import { NextResponse } from "next/server";
import { readProducts, addProduct } from "@/lib/productsStore";

export async function GET() {
  const products = await readProducts();
  return NextResponse.json(products);
}

export async function POST(request: Request) {
  try {
    const newProductData = await request.json();
    // ID is now generated by addProduct, so we don't pass it
    const { id, ...data } = newProductData;
    const createdProduct = await addProduct(data);
    return NextResponse.json(createdProduct, { status: 201 });
  } catch (e: any) {
    return NextResponse.json(
      { error: e.message || "Failed to create product" },
      { status: 400 }
    );
  }
}